openapi: 3.0.4
info:
  title: Eventix Booking Service API
  description: |
    This is the API specification for the Eventix Booking Service.
    It allows clients to create, view, update, and delete event bookings,
    and retrieve detailed analytics such as recent bookings, wishlists, and ratings.
 
    - Version: 1.0.0
    - Base URL: http://localhost:8080
  termsOfService: https://eventix.io/terms/
  contact:
    email: support@eventix.io
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
 
servers:
  - url: http://localhost:8080
    description: Local development server
 
tags:
  - name: Booking
    description: Operations related to bookings
  - name: Stats
    description: Booking statistics and analytics
 
paths:
  /bookings:
    get:
      tags:
        - Booking
      summary: Get all bookings
      description: Retrieve a list of all bookings in the system.
      operationId: getBookings
      responses:
        '200':
          description: List of bookings retrieved successfully.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Booking'
        '500':
          description: Server error
 
    post:
      tags:
        - Booking
      summary: Create a new booking
      description: Create a booking for an event.
      operationId: createBooking
      requestBody:
        description: Booking data to create a new record.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookingRequest'
      responses:
        '201':
          description: Booking created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Booking'
        '400':
          description: Invalid booking data provided.
        '500':
          description: Server error.
 
  /bookings/{id}:
    get:
      tags:
        - Booking
      summary: Get booking by ID
      description: Retrieve a specific booking by its ID.
      operationId: getBookingById
      parameters:
        - name: id
          in: path
          required: true
          description: Booking ID
          schema:
            type: integer
      responses:
        '200':
          description: Booking found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Booking'
        '404':
          description: Booking not found.
 
    put:
      tags:
        - Booking
      summary: Update booking by ID
      description: Modify details of an existing booking.
      operationId: updateBooking
      parameters:
        - name: id
          in: path
          required: true
          description: Booking ID
          schema:
            type: integer
      requestBody:
        description: Updated booking data.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookingRequest'
      responses:
        '200':
          description: Booking updated successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Booking'
        '404':
          description: Booking not found.
 
    delete:
      tags:
        - Booking
      summary: Delete booking by ID
      description: Remove a booking from the system by ID.
      operationId: deleteBooking
      parameters:
        - name: id
          in: path
          required: true
          description: Booking ID
          schema:
            type: integer
      responses:
        '204':
          description: Booking deleted successfully.
        '404':
          description: Booking not found.
 
  /stats:
    get:
      tags:
        - Stats
      summary: Get detailed event statistics
      description: Retrieve analytics including total bookings, wishlists, average rating, and more.
      operationId: getEventStats
      parameters:
        - name: eventId
          in: query
          required: false
          description: Filter stats by specific event ID
          schema:
            type: integer
        - name: city
          in: query
          required: false
          description: Filter stats by city
          schema:
            type: string
        - name: category
          in: query
          required: false
          description: Filter stats by category
          schema:
            type: string
      responses:
        '200':
          description: Statistics retrieved successfully.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EventStats'
        '500':
          description: Server error.
 
components:
  schemas:
    Booking:
      type: object
      properties:
        id:
          type: integer
          example: 101
        eventId:
          type: integer
          example: 202
        userId:
          type: integer
          example: 301
        userName:
          type: string
          example: John Doe
        userEmail:
          type: string
          example: john.doe@email.com
        tickets:
          type: integer
          example: 2
        totalAmount:
          type: number
          format: double
          example: 150.0
        bookingDate:
          type: string
          format: date-time
          example: 2025-11-02T10:30:00Z
        city:
          type: string
          example: Mumbai
        category:
          type: string
          example: Music
 
    BookingRequest:
      type: object
      required:
        - eventId
        - userId
        - userName
        - userEmail
        - tickets
      properties:
        eventId:
          type: integer
          example: 202
        userId:
          type: integer
          example: 301
        userName:
          type: string
          example: John Doe
        userEmail:
          type: string
          example: john.doe@email.com
        tickets:
          type: integer
          example: 2
        city:
          type: string
          example: Mumbai
        category:
          type: string
          example: Music
 
    EventStats:
      type: object
      properties:
        eventId:
          type: integer
          example: 202
        totalBookings:
          type: integer
          example: 150
        recentBookings:
          type: integer
          example: 12
        wishlistCount:
          type: integer
          example: 58
        avgRating:
          type: number
          format: float
          example: 4.6
        userId:
          type: integer
          example: 301
        timestamp:
          type: string
          format: date-time
          example: 2025-11-02T12:00:00Z
        city:
          type: string
          example: Mumbai
        category:
          type: string
          example: Music Festival